from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    database_url: str = "postgresql+asyncpg://segue:segue@postgres:5432/segue"
    redis_url: str = "redis://redis:6379/0"
    kafka_brokers: str = "redpanda:9092"
    rabbit_url: str = "amqp://segue:segue@rabbitmq:5672/"
    web_origin: str = "http://localhost:3000"

    # clef-flash, reached through typesafe-sdk with a custom base URL.
    model_base_url: str = "http://172.16.124.162:4040"
    model_api_key: str = "local"
    model_name: str | None = None
    model_timeout_s: float = 4.0

    airlabs_api_key: str = ""
    airlabs_budget: int = 900  # hard stop below the plan's 1,000 queries

    # Secrets: generated by scripts/init_env.py, never committed.
    pii_key: str = ""  # Fernet key for personal-data columns
    session_secret: str = "change-me"
    seed_staff_password: str = ""

    retention_hours: int = 24  # personal data is purged this long after the outbound flight departs
    notice_version: str = "2026-10-01"
    grievance_contact: str = "privacy@segue.example"

    # Confidence gating.
    gate_auto: float = 0.85
    gate_approval: float = 0.5

    # Rule fallback thresholds on the time buffer (minutes), used when the model is unavailable.
    rule_safe_min: int = 20
    rule_tight_min: int = 5
    rule_risk_min: int = -15

    airports_dir: str = "/app/config/airports"


@lru_cache
def get_settings() -> Settings:
    return Settings()
