from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    database_url: str = "postgresql+asyncpg://segue:segue@postgres:5432/segue"
    redis_url: str = "redis://redis:6379/0"
    kafka_brokers: str = "redpanda:9092"
    rabbit_url: str = "amqp://segue:segue@rabbitmq:5672/"
    web_origin: str = "http://localhost:3000"

    # clef-flash, reached through typesafe-sdk with a custom base URL.
    model_base_url: str = "http://172.16.124.162:4040"
    model_api_key: str = "local"
    model_name: str | None = None
    model_timeout_s: float = 4.0
    model_concurrency: int = 8   # passenger questions for one connection are asked this many at a time
    model_fake: bool = False     # benchmark only: answer instantly from the policy, with no model call
    topic_partitions: int = 6    # lets several engine instances share the events, one flight always on one partition

    airlabs_api_key: str = ""
    airlabs_budget: int = 900  # hard stop below the plan's 1,000 queries
    airlabs_passenger_share: float = 0.6  # passenger searches stop here; the rest is kept for the poller

    # Secrets: generated by scripts/init_env.py, never committed.
    pii_key: str = ""  # Fernet key for personal-data columns
    jwt_signing_secret: str = ""
    access_token_minutes: int = 15
    refresh_token_hours: int = 8
    passenger_token_hours: int = 72
    cookie_secure: bool = False  # set COOKIE_SECURE=true once the site is served over HTTPS
    seed_staff_password: str = ""  # old shared password: read once, to move existing accounts to their own
    seed_password_ops: str = ""
    seed_password_crew: str = ""
    seed_password_ground: str = ""
    seed_password_authority: str = ""
    seed_password_admin: str = ""
    max_passengers_per_connection: int = 600
    max_streams_per_session: int = 6

    # Mail. The default is the Mailpit container: a local test inbox, nothing leaves the machine.
    smtp_host: str = "mailpit"
    smtp_port: int = 1025
    smtp_user: str = ""
    smtp_password: str = ""
    smtp_starttls: bool = False
    smtp_tls: bool = False       # implicit TLS (port 465)
    mail_per_address_per_hour: int = 20
    mail_from: str = "Segue <no-reply@segue.local>"
    official_map_url: str = "https://dubaiairports.ae/information/transfers"

    retention_hours: int = 24  # personal data is purged this long after the outbound flight departs
    notice_version: str = "2026-10-01"
    grievance_contact: str = "privacy@segue.example"

    # Confidence gating.
    gate_auto: float = 0.85
    gate_approval: float = 0.5

    # Rule fallback thresholds on the time buffer (minutes), used when the model is unavailable.
    rule_safe_min: int = 20
    rule_tight_min: int = 5
    rule_risk_min: int = -15

    # A suggested hold aims to bring the buffer up to this, and never exceeds the cap.
    hold_target_buffer_min: int = 10
    hold_max_min: int = 15

    airports_dir: str = "/app/config/airports"


    @property
    def jwt_secret(self) -> str:
        """No default and no fallback: a missing or short secret stops the service instead of signing with a guessable key."""
        if len(self.jwt_signing_secret.encode()) < 32:
            raise RuntimeError("JWT_SIGNING_SECRET is missing or shorter than 32 bytes. Run scripts/init_env.py to generate secrets.")
        return self.jwt_signing_secret


@lru_cache
def get_settings() -> Settings:
    return Settings()
